name: Latest
on: push
jobs:
  actions:
    runs-on: ubuntu-latest
    env:
      github_sha: ${{ github.sha }}
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen con entorno de desarrollo
      run: docker build --tag islasgeci/pde:latest --tag islasgeci/pde:${github_sha:0:4} .
    - name: Verifica el formato de los scripts
      run: docker run --volume ${PWD}:/workdir islasgeci/pde:latest make check
    - name: Ejecuta las pruebas de la imagen
      run: docker run --volume ${PWD}:/workdir islasgeci/pde:latest make tests
    - name: Docker log-in
      env:
        docker_username: ${{ secrets.docker_username }}
        docker_password: ${{ secrets.docker_password }}
      run: echo "${docker_password}" | docker login -u "${docker_username}" --password-stdin
    - name: Sube latest a Docker Hub
      run: docker push islasgeci/pde:latest
    - name: Sube sha a Docker Hub
      run: docker push islasgeci/pde:${github_sha:0:4}
