name: Latest
on: push
jobs:
  actions:
    runs-on: ubuntu-latest
    env:
      github_sha: ${{ github.sha }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Remove lock file
      run: rm flake.lock
    - name: Build Docker image
      run: docker build --tag islasgeci/pde:latest --tag islasgeci/pde:${github_sha:0:4} .
    - name: Run tests
      run: docker run --volume ${PWD}:/workdir islasgeci/pde:latest make tests
    - name: Docker log-in
      env:
        docker_username: ${{ secrets.docker_username }}
        docker_password: ${{ secrets.docker_password }}
      run: echo "${docker_password}" | docker login -u "${docker_username}" --password-stdin
    - name: Push latest image to Docker Hub
      run: docker push islasgeci/pde:latest
    - name: Push tegged image to Docker Hub
      run: docker push islasgeci/pde:${github_sha:0:4}
    - name: Auto-commit flake.lock
      uses: stefanzweifel/git-auto-commit-action@master
      with:
        commit_message: 🤖 Commit lock file
        file_pattern: 'flake.lock'
        commit_user_name: Ciencia de Datos • GECI
        commit_user_email: ciencia.datos@islas.org.mx
